
import type {Metadata} from 'next';
import './globals.css';
import RouteMemory from "@/components/RouteMemory";
import EdgeSwipeBack from '@/components/EdgeSwipeBack';
import ClientShell from '@/components/ClientShell';
import { TradeAccountProvider } from '@/context/tradeAccount';

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        <TradeAccountProvider>
          <RouteMemory />
          <EdgeSwipeBack />
          <ClientShell>{children}</ClientShell>
        </TradeAccountProvider>
      </body>
    </html>
  );
}
